name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      MISE_ENV: ci
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          experimental: true
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends zsh
          gcc-multilib g++-multilib device-tree-compiler
      - name: Lua typecheck and linting
        run: mise run lint
      - name: Dry-run tests
        run: mise run test
        env:
          DRY_RUN: 1
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/west
            ~/.local/share/mise
          key: ${{ runner.os }}-west-${{ hashFiles('mise.ci.toml') }}
      - name: Run tests
        run: mise run test --timeout 10m
