name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        zephyr-sdk-version: [0.17.0, latest]
        os: [ubuntu-latest,macos-latest]
    runs-on: ${{matrix.os}}
    env:
      MISE_ENV: ci
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          experimental: true
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/west
            ~/.local/share/mise
          key: ${{ runner.os }}-west-${{ hashFiles('mise.ci.toml') }}
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run:
          sudo apt-get update && sudo apt-get install -y --no-install-recommends zsh
          gcc-multilib g++-multilib device-tree-compiler
      - name: Lua typecheck and linting
        run: mise run lint
      - name: Smoke test llvm variant
        run: mise run test_e2e:toolchain:version arm@${{matrix.zephyr-sdk-version}} --timeout 10m
      - name: Smoke test llvm variant
        if: matrix.zephyr-sdk-version == 'latest'
        run:
          mise run test_e2e:toolchain:version llvm@latest --timeout 10m
      - name: Smoke test gnuarmemb variant
        if: matrix.zephyr-sdk-version == 'latest'
        run:
          mise run test_e2e:toolchain:version gnuarmemb@latest --timeout 10m
